/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogidRouteImport } from './routes/$blogid'
import { Route as IndexRouteImport } from './routes/index'

const BlogidRoute = BlogidRouteImport.update({
  id: '/$blogid',
  path: '/$blogid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$blogid': typeof BlogidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$blogid': typeof BlogidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$blogid': typeof BlogidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$blogid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$blogid'
  id: '__root__' | '/' | '/$blogid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogidRoute: typeof BlogidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$blogid': {
      id: '/$blogid'
      path: '/$blogid'
      fullPath: '/$blogid'
      preLoaderRoute: typeof BlogidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogidRoute: BlogidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
